name: Node.js Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sundays at midnight

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with Jest
        run: npm test -- --ci --coverage --testLocationInResults
        continue-on-error: false

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Upload Jest test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
