name: Node.js Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sundays at midnight

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with Jest and generate reports
        run: |
          mkdir -p test-results logs
          npx jest --ci --coverage \
            --outputFile=test-results/junit.xml \
            --testLocationInResults \
            --reporters=default \
            --reporters=jest-junit \
            | tee logs/test-output.log

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/junit.xml

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/test-output.log
